version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile_server
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile_frontend
    ports:
      - "3000:3000"
